# name of the website
name: "Alia's Art Gallery"
# github pages url
baseurl: https://XinYaanZyoy.github.io
# repository name
scope: Art_Gallery
# color of the theme on android phones
theme_color: "#d80247"
# greetings on the gome page
greeting: "Hi!"
# author of the website
author: "Alia Bhatt"
# heading on the home and about page
heading: "This is my Art Gallery"
# icon for browser
favicon: "assets/img/favicon.ico"
# logo for home and about page
logo: "assets/img/logo.png"
# author's personal pic for about page
pic: "assets/img/me.jpg"
# author's email
email: "AliaBhatt@email.com"
# author's socials
twitter: https://twitter.com/aliaa08
facebook: 
instagram: https://www.instagram.com/aliaabhatt/
youtube: https://www.youtube.com/channel/UC8iJjhq3c1K1Mc-jpl51EKg
whatsapp:
# description of this website for about page and google search
description: "the digital collection of my arts"
collections:
  arts:
    output: true
    art: true
  captions:
    output: true
    caption: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-books

theme: jekyll-theme-cayman
