name: entrier

on: 
  push:
    paths: 
      - 'arts/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: trilom/file-changes-action@v1.2.3
        with:
          token: ${{secrets.GH_PAT}}
